# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2328eab19ac1fe46d06f4bb279db3a2a5adaf6e9fd46658dab5fa57837d81b65faeb00bda7eb6fd8c397b2d715eac1c033720aba72685af6acd6f5914c9f9c76

test:
  secret_key_base: c43eaee116049c45a172496ca61fb3690690e813f53c23cd0d604b066490735d2a6bfeac95a949546474cab453daabea82c95bc45b70efcb0dc711010261dde6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
